providers:
  docker:
    network: sample-net
    exposedbydefault: false

# API configuration
api:
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

  metrics:
    address: :8082

metrics:
  prometheus:
    addRoutersLabels: true
    addEntryPointsLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    entryPoint: metrics
